version: '3.3'
services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      tz: 'gmt-6'
      pgtz: 'gmt-6'
    ports:
      - '5435:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/mydata
volumes:
  postgres_data: {}
